//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClusterLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClusterLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo no activado. Este nodo tiene menos adaptadores validos que el remoto.
        /// </summary>
        internal static string ActivateNumAdaptersError {
            get {
                return ResourceManager.GetString("ActivateNumAdaptersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeout intentando activar el nodo.
        /// </summary>
        internal static string ActivateTimeout {
            get {
                return ResourceManager.GetString("ActivateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adaptador 1.
        /// </summary>
        internal static string Adapter1 {
            get {
                return ResourceManager.GetString("Adapter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adaptador 2.
        /// </summary>
        internal static string Adapter2 {
            get {
                return ResourceManager.GetString("Adapter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detectado adaptador {0} ({1}).
        /// </summary>
        internal static string AdapterDetected {
            get {
                return ResourceManager.GetString("AdapterDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adaptador {0} ({1}) no operacional.
        /// </summary>
        internal static string AdapterNotOperational {
            get {
                return ResourceManager.GetString("AdapterNotOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo ya activo desde {0}.
        /// </summary>
        internal static string AlreadyActivate {
            get {
                return ResourceManager.GetString("AlreadyActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo ya desactivado desde {0}.
        /// </summary>
        internal static string AlreadyDeactivate {
            get {
                return ResourceManager.GetString("AlreadyDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo Local:\n{0}\nNodo Remoto:\n{1}.
        /// </summary>
        internal static string ClusterInfo {
            get {
                return ResourceManager.GetString("ClusterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error creando Ip de cluster.
        /// </summary>
        internal static string CreateIpError {
            get {
                return ResourceManager.GetString("CreateIpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo desactivado al no estar operativos los adaptadores.
        /// </summary>
        internal static string DeactivateByNotAdapters {
            get {
                return ResourceManager.GetString("DeactivateByNotAdapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error desactivando nodo. El nodo remoto tiene menos adaptadores validos que el actual.
        /// </summary>
        internal static string DeactivateNumAdaptersError {
            get {
                return ResourceManager.GetString("DeactivateNumAdaptersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error desactivando nodo. El nodo remoto no esta operativo.
        /// </summary>
        internal static string DeactivateValidRemoteNodeError {
            get {
                return ResourceManager.GetString("DeactivateValidRemoteNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error borrando Ip de cluster.
        /// </summary>
        internal static string DeleteIpError {
            get {
                return ResourceManager.GetString("DeleteIpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detectados dos nodos activos al mismo tiempo.
        /// </summary>
        internal static string DetectedTwoActiveNodesError {
            get {
                return ResourceManager.GetString("DetectedTwoActiveNodesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saliendo de la aplicacion.
        /// </summary>
        internal static string ExitApplication {
            get {
                return ResourceManager.GetString("ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo desactivado por encontrarse las Ip de cluster en la red.
        /// </summary>
        internal static string FoundClusterIps {
            get {
                return ResourceManager.GetString("FoundClusterIps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibida peticion local de activacion.
        /// </summary>
        internal static string LocalActivateAsk {
            get {
                return ResourceManager.GetString("LocalActivateAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo desactivado por peticion local.
        /// </summary>
        internal static string LocalDeactivateAsk {
            get {
                return ResourceManager.GetString("LocalDeactivateAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error parseando mensaje del nodo remoto.
        /// </summary>
        internal static string NewDataError {
            get {
                return ResourceManager.GetString("NewDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo activado.
        /// </summary>
        internal static string NodeActive {
            get {
                return ResourceManager.GetString("NodeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo no operativo.
        /// </summary>
        internal static string NodeNotOperational {
            get {
                return ResourceManager.GetString("NodeNotOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No operativo.
        /// </summary>
        internal static string NotOperational {
            get {
                return ResourceManager.GetString("NotOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error procesando las tareas periodicas.
        /// </summary>
        internal static string PeriodicTaskError {
            get {
                return ResourceManager.GetString("PeriodicTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibido estado de nodo remoto\n{0}.
        /// </summary>
        internal static string ReceivedRemoteNodeState {
            get {
                return ResourceManager.GetString("ReceivedRemoteNodeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibida peticion remota de activacion.
        /// </summary>
        internal static string RemoteActivateAsk {
            get {
                return ResourceManager.GetString("RemoteActivateAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo desactivado por peticion remota.
        /// </summary>
        internal static string RemoteDeactivateAsk {
            get {
                return ResourceManager.GetString("RemoteDeactivateAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo no activado. El nodo remoto ya esta en proceso de activacion.
        /// </summary>
        internal static string RemoteNodeActivating {
            get {
                return ResourceManager.GetString("RemoteNodeActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha dejado de recibirse presencias del nodo remoto.
        /// </summary>
        internal static string RemoteNodeNotOperational {
            get {
                return ResourceManager.GetString("RemoteNodeNotOperational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error enviando mensaje a nodo remoto.
        /// </summary>
        internal static string SendError {
            get {
                return ResourceManager.GetString("SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ini. del estado.
        /// </summary>
        internal static string StateBegin {
            get {
                return ResourceManager.GetString("StateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Org. del estado.
        /// </summary>
        internal static string StateCause {
            get {
                return ResourceManager.GetString("StateCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recibido tipo de mensaje desconocido.
        /// </summary>
        internal static string UnknownMsgType {
            get {
                return ResourceManager.GetString("UnknownMsgType", resourceCulture);
            }
        }
    }
}
